name: Latifundia
version: '${project.version}'
main: net.uber.latifundia.Latifundia
api-version: '1.20'
commands:
  latifundia:
    description: Base command for Latifundia
    aliases: [lf]
    usage: /<command> <subcommand> [arguments]
    permission: latifundia.use
    permission-message: You do not have permission to use this command.
    subcommands:
      claim:
        description: Claim a land
        usage: /<command> claim
        permission: latifundia.claim
      unclaim:
        description: Unclaim a land
        usage: /<command> unclaim
        permission: latifundia.unclaim
      info:
        description: Get information about a land
        usage: /<command> info
        permission: latifundia.info
      abandon:
        description: Abandons and deletes the citystate
        usage: /<command> abandon
        permission: latifundia.abandon
      create:
        description: Creates a new citystate
        usage: /<command> create
        permission: latifundia.create
      leave:
        description: Leaves the citystate
        usage: /<command> leave
        permission: latifundia.leave
